### ISSUE TITLE
Maybe an update is needed for 0.9.0

### ISSUE THREAD

**Issue by henkiewie** [rusty-bits/octool#12]
Hi rusty 😄 ,

Maybe theres an update needed for 0.9.0 ?
Or is there reaaly something wrong with the hash?
They are equal.
```
Checking local OpenCorePkg 0.9.0 binaries ... "OpenCore-0.9.0-RELEASE" local copy not found, Downloading
remote hash 156fc6371e07dc17c3363e5da1812c1df5355782e1f5e1895b3ded3be1b8158b
  local sum a036578d90d783bde5aad5be6f4eb8b9b1569e67e748f1f381cb2713b3f633fa
thread 'main' panicked at 'Sum of "resources/OpenCore-0.9.0-RELEASE/OpenCore-0.9.0-RELEASE.zip" does not match 156fc6371e07dc17c3363e5da1812c1df5355782e1f5e1895b3ded3be1b8158b', src/res.rs:285:13
                             note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                                                          zsh: abort      ./octool -V 0.9.0
```

regards,
Henk

**Comment by rusty-bits** [comment]
not really anything to do at the moment, for some reason the config.json and latest.json files of the Dortania builds repo have the "wrong" sha256 in them and the panic that octool is doing is my "graceful" way of letting you know there is an issue

**Comment by rusty-bits** [comment]
talked to the dortania builds maintainer and he said it should be fixed soon

**Comment by henkiewie** [comment]
OK thanks for the quick responce. Close the issue and wait for a fix. It will show with the following pre releases of 0.9.0.

**Comment by rusty-bits** [comment]
that's assuming the latest build he just kicked off will include the correct sum, lol

**Comment by henkiewie** [comment]
It was already fixed. 👍
