### ISSUE TITLE
octool Working Great!!

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/octool#3]
I decided to give octool another try. Updated opencore to 0.7.6, worked perfectly.

The only kext I added to the input was the recently released RadeonSensor.kext. would it be possible for octool to pull it from the repo?

<img width="862" alt="Screenshot 2021-12-06 at 23 42 34" src="https://user-images.githubusercontent.com/2873112/144940735-ca8381a5-edbc-4649-9eec-0b4daf44525f.png">

Thank You

**Comment by rusty-bits** [comment]
glad it's working, I will see if I can add the RadeonSensor on the next release

**Comment by rusty-bits** [comment]
added RadeonSensor with latest commit 0cd7062
