### ISSUE TITLE
 No schema for SerialInit

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/octool#6]
If I set True or False I'm still getting an error. still boots without issues.

<img width="884" alt="Screenshot 2022-04-18 at 16 11 36" src="https://user-images.githubusercontent.com/2873112/163829823-5f9226fd-ec09-4e7d-ae55-2e9e89bd94dd.png">

<img width="884" alt="Screenshot 2022-04-18 at 16 27 21" src="https://user-images.githubusercontent.com/2873112/163831829-c21a712d-97ce-4df1-9a99-888edffc51c5.png">

Thanks

**Comment by rusty-bits** [comment]
SerialInit does not exist in OpenCore 0.8.0 which is why ocvalidate is giving an error that there is no schema for SerialInit  

It doesn't matter if you make it true or false, it shouldn't be there at all.  You'll need to delete it if you don't want ocvalidate showing an error.

**Comment by Blurayx** [comment]
According to the release notes, it's been added, or is this something else?

<img width="826" alt="Screenshot 2022-04-18 at 20 58 14" src="https://user-images.githubusercontent.com/2873112/163869100-5eea0ab8-e46b-40af-a664-167674d64b30.png">

**Comment by rusty-bits** [comment]
That is the Misc > Serial section that was added, the error you have is for Debug > SerialInit which was removed.

**Comment by Blurayx** [comment]
Ah, thanks.
