### ISSUE TITLE
New options for 0.8.1

### ISSUE THREAD

**Issue by henkiewie** [rusty-bits/octool#7]
The new  driver efi files for ResetNvramEntry.efi and ToggleSipEntry.efi have to be in the input directory. They are not fetched automatically. Also the obsolete entries are not removed.

**Comment by rusty-bits** [comment]
Thank you for pointing out those additions, I had added them to my local build a while ago but totally forgot to push the update.  
For the other issue, I don't know what you mean by "the obsolete entries are not removed," could you explain it to me a little more?

**Comment by henkiewie** [comment]
Yes, I already uprgaded to 4.0. 😄.
They are the old entries to get them in the menu in Misc/security AllowNvramReset and AllowToggleSip.
I removed them by hand so I didn't test with 4.0

**Comment by rusty-bits** [comment]
Hmm, it shouldn't matter what version of octool you're on for that to work.  Octool is not tied to a particular version of OpenCore, it just lets you select which version of OpenCore EFI you want to build from the list of available versions it sees from Acidanthera.   

pressing capital V in the editor lets you choose an OpenCore version  
pressing capital M (merge) will add in missing fields depending on what version of OpenCore you selected  
pressing capital P (purge) will remove fields that no longer belong depending on the version of OpenCore you selected  

Did you use the purge command when you were on octool 0.3.9 and it didn't work?

**Comment by henkiewie** [comment]
I think it does. I made a copy with 0.3.9 and the content of a config.plist with the values still there.
I started with `./octool -o 0.8.1` and ocvalidate found the two errors.
```NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.1!
OCS: No schema for AllowNvramReset at 0 index, context <Security>!
OCS: No schema for AllowToggleSip at 2 index, context <Security>!
Serialisation returns 2 errors!
Completed validating /Users/henk/octool3/INPUT/config.plist in 2 ms. Found 2 issues requiring attention.
```
After pressing Capital P i got;

```
Removed Misc->Security->AllowNvramReset
Removed Misc->Security->AllowToggleSip
```
And after pressing Capital G

```
Validating OUTPUT/EFI/OC/config.plist
NOTE: This version of ocvalidate is only compatible with OpenCore version 0.8.1!
Completed validating OUTPUT/EFI/OC/config.plist in 3 ms. No issues found.
```

So you have to do by hand.
Time to close the issue 😃

**Comment by rusty-bits** [comment]
Ah, good, thank you for checking.
