### ISSUE TITLE
[Feature Request] OpenCanopy Resources override

### ISSUE THREAD

**Issue by dreamwhite** [rusty-bits/octool#8]
I don't know if this topic has already been discovered or not but... In case you wanna use a custom `Resources` folder (e.g. no `Audio` folder or dropped themes) it would be very convenient to specify a custom `Resources` folder in `INPUT` directory that will be copied during the EFI building process.
What do you think about it? Is this thing achievable?
Greetings
dreamwhite

**Comment by rusty-bits** [comment]
I'm not quite sure what feature you're asking for.  As it stands right now, octool will already copy custom Resources like audio, themes, etc. to the OUTPUT/EFI if you place them in the INPUT/Resources folder.  

If OpenCanopy.efi is enabled in your config.plist then octool will first copy the standard Acidanthera/Resources to the OUTPUT/EFI and will then copy any INPUT/Resources you have to the OUTPUT/EFI  

If OpenCanopy.efi is not enabled then it won't copy any of the Resources  

Could you explain it better to me if there is something additional you would like octool to do?

**Comment by dreamwhite** [comment]
Hi, thank you so much for your reply and the effort you're putting on this project. Actually it seems that `octool v0.4.1 2022-06-12` doesn't copy a custom `Resources` folder even if it's already in `INPUT` folder.

See screenshot below:

![image](https://user-images.githubusercontent.com/17933708/176051119-31061d20-c133-45a5-a16e-698a071d1d8a.png)

Building the EFI via `Shift+G` actually returns the following log:

![image](https://user-images.githubusercontent.com/17933708/176051164-64f106a0-4ec6-473a-b365-1e47e5fbcf9d.png)

and the `OUTPUT/EFI/OC/Resources` folder doesn't contain at all the custom `Resources` I specified before:

![image](https://user-images.githubusercontent.com/17933708/176051365-11b72d0b-cc21-4c03-898e-358e6c4dc69f.png)


From what I'm seeing the custom `INPUT/Resources` folder is totally skipped. Is this an issue or am I missing something?
Thank you so much in advance and have a nice day :)

**Comment by dreamwhite** [comment]
I think that the issue is on this [line](https://github.com/rusty-bits/octool/blob/65f41b37dd167420379d81da0d1accbe1423eed5/src/build.rs#L143)

It should do something along the lines of:

1. If there's no `Resources` directory in `INPUT` or it contains empty directories (`Audio`, `Font`, `Image` and `Label`) then it copies `OcBinaryData/Resources` directory in `OUTPUT/EFI/OC`
2. Otherwise it copies `Resources` directory from `INPUT` to `OUTPUT/EFI/OC`.

I'm not a RUST dev yet, but I'm willing to test artifacts if needed.
I'm willing to leave my contacts if needed. Let me know

Greetings
dreamwhite

**Comment by rusty-bits** [comment]
Ah, I think I understand what you want it to do now.  
You're looking for an either/or type of situation in which octool will totally ignore OcBinaryData if there are Resources in the INPUT folder.  

I don't know if that's a great idea since I've seen many people forget to include some OpenCanopy Resources they didn't think were important, and then they couldn't figure out why their EFI wouldn't use OpenCanopy at all.  

As of now octool will copy all the OcBinaryData to the OUTPUT/EFI when it sees that OpenCanopy is enabled.  It will then copy any INPUT/Resources on top of the OUTPUT/EFI/OC/Resources  

But,  **it doesn't tell you that it is doing this last part**  

So, that's an issue of me being lazy (if I remember correctly)  

I made a quick change to the output messages, how does something like this look?  


```
Copying enabled Misc files ...
No files to copy


Copying enabled UEFI files ...
"resources/OpenCore-0.8.2-RELEASE/X64/EFI/OC/Drivers/OpenRuntime.efi"
"resources/OpenCore-0.8.2-RELEASE/X64/EFI/OC/Drivers/OpenCanopy.efi"
done with 2 files

Found OpenCanopy.efi Enabled in UEFI->Drivers
Copying 76 Audio resources from OcBinaryData ... done
Copying 1 Audio resource from IPUT/Resources ... done
Copying 4 Font resources from OcBinaryData ... done
Copying 1 Image resource from OcBinaryData ... done
Copying 1 Image resource from IPUT/Resources ... done
Copying 22 Label resources from OcBinaryData ... done

Found Misc->Security->Vault set to Secure
Computing vault.plist ... done
Signing OpenCore.efi ... done
```

**Comment by dreamwhite** [comment]
Yeah something like that is fine but actually I see useless copying `OCBinaryData` stuff on the disk if there's already a `Resources` valid folder... Given that 100MB written on a disk shouldn't create any issue, it's still better copying only when needed

**Comment by rusty-bits** [comment]
Well, there wouldn't be a Resources folder of any type since octool deletes the OUTPUT folder entirely when you build an EFI with the 'G' command.  

It needs to guarantee that what you requested is actually what is built, especially if you are using features like secure boot and vaulting (which I always have as Secure for example)

**Comment by dreamwhite** [comment]
> Well, there wouldn't be a Resources folder of any type since octool deletes the OUTPUT folder entirely when you build an EFI with the 'G' command.
> 
> It needs to guarantee that what you requested is actually what is built, especially if you are using features like secure boot and vaulting (which I always have as Secure for example)

Yeah of course this makes sense. Sorry if I couldn't explain my feature request (low sleep, not native language and so on) but basically in my mind it makes absolutely sense to check first if the user specifies a custom `Resources` folder in `INPUT` and when using `G` command it builds the EFI using that custom previously specified `Resources` folder

**Comment by rusty-bits** [comment]
Don't apologize, what you're suggesting does make sense.  I will see if I can make any improvements to the method octool uses, and for now I will add the additional output messages that explain what octool is copying.

**Comment by dreamwhite** [comment]
Thank you so much ^^ Feel free to disturb me on Telegram if needed: [@dreamwhitedev](https://t.me/dreamwhitedev)

**Comment by rusty-bits** [comment]
Okay, made some changes  

If a Resource folder with items inside it exists in the INPUT folder, then octool will copy that to the OUTPUT/EFI  
otherwise, octool will copy the specific OcBinaryData folder to the OUTPUT/EFI  


![Screenshot 2022-06-28 at 5 31 41 PM](https://user-images.githubusercontent.com/46965981/176302265-f6e093f9-6c6f-4391-ad55-4d56135a3502.png)

Hopefully I didn't mess too many things up!  :)

**Comment by rusty-bits** [comment]
My only other question for you if why do you have so many things inside your INPUT folder?   

The only things inside the INPUT folder should be items that you don't want octool to update by itself, you should never have things like AppleALC.kext, Lilu.kext VirtualSMC.kext inside the INPUT folder.

**Comment by dreamwhite** [comment]
> My only other question for you if why do you have so many things inside your INPUT folder?   
> 
> 
> 
> The only things inside the INPUT folder should be items that you don't want octool to update by itself, you should never have things like AppleALC.kext, Lilu.kext VirtualSMC.kext inside the INPUT folder.   

Yeah, you're right. Honestly I decided to add them as a test just for speed purposes (copying rather than downloading, unzipping etc).

P.S. given that probably I'd have to open a new issue, how do you handle VoodooInput conflict between VoodooPS2 and VoodooI2C? They have some differences apparently and only VooodooI2C version of VoodooInput should be installed

**Comment by dreamwhite** [comment]
Good morning! I successfully tested `octool v0.4.2 2022-06-28` and it works as expected!
Just a few things I'd like to change:

1. if a custom valid `Resources` folder is added in `INPUT`, `OCBinaryData` should be ignored at all, even if there are empty dirs (such as `Audio`). There are some cases where user wants only a GUI without the typical `dong`
2. Some kexts contain `Resources` sub-folder (such as `SMCBatteryManager`) as well as `.dSYM` symbols. Can they eventually be removed? They aren't used at all in usual configs. The pseudo-code should be something like: `for each kext in the downloaded one check if there's a Resources or a .dSYM file/folder and remove it`

Again thank you so much for the effort :smile:

**Comment by rusty-bits** [comment]
> given that probably I'd have to open a new issue...  

Don't worry about opening new issues, as to your current points  

> how do you handle VoodooInput conflict between VoodooPS2 and VoodooI2C? They have some differences apparently and only VooodooI2C version of VoodooInput should be installed  

From what I've been told there is no difference in the VoodooInput kexts, either the VoodooInput.kext itself or the copy bundled with VoodooPS2, VoodooI2C, etc.  
The only _issue_ is you can only have one enabled.  So, only enable one of them in your config.plist or even better, only include one of them in your config.plist  
I'm just trying to avoid having octool guess what the user intended and avoid requiring octool to make changes to the kexts it copies over  

> if a custom valid Resources folder is added in INPUT, OCBinaryData should be ignored at all, even if there are empty dirs (such as Audio). There are some cases where user wants only a GUI without the typical dong  

I don't think I will ever ignore OcBinaryData, in fact I may revert back to the process I was using before where all the OcBinaryData is copied over and if the user has any differences in the INPUT folder then they will be copied on top of the OUTPUT/EFI/OC/Resources  
This will ensure that there will be no boot failures if the user made a mistake in their INPUT/Resources folders, I'm just waiting to see if any issues arise from my changes.  

I understand this means the OUTPUT/EFI/OC/Resources will not be a mirror of the INPUT/Resources unless the user adds a dummy blank file to the INPUT/Resources folder e.g. INPUT/Resources/Audio/this_is_empty  

As to a user wanting a GUI without the typical dong they should not be enabling the startup chime in their config.plist, it has nothing to do with what files are included in their EFI/OC/Resources  

> Some kexts contain Resources sub-folder (such as SMCBatteryManager) as well as .dSYM symbols. Can they eventually be removed? They aren't used at all in usual configs.  

Possibly, but as I said before I want to avoid having octool make changes to the kexts it copies over
