### ISSUE TITLE
[Feature Request] New add templates

### ISSUE THREAD

**Issue by dreamwhite** [rusty-bits/octool#9]
Thank you so much for the effort you're putting in this project.
It would be very useful having a `add` template for the following entries in the config.plist:

- `ACPI/Delete`
- `ACPI/Patch`
- `Booter/MmioWhitelist`
- `Booter/Patch`
- `DeviceProperties/Add`
- `Kernel/Block`
- `Kernel/Force`
- `Kernel/Patch`
- `Misc/BlessOverride`
- `Misc/Entries`

What are your thoughts on this? Is this thing achievable?
Greetings
dreamwhite

**Comment by rusty-bits** [comment]
Ah, yes, you are correct.  I will try to add those on when I have some free time.

**Comment by rusty-bits** [comment]
For now the end user can just copy and paste an existing entry, then edit that entry, but it would be easier to have the top entry in the add list do that for you.

**Comment by rusty-bits** [comment]
okay, done  

I just had octool repeat the same thing it did for the other "templates", read the first item out of the Sample.plist for the selected section if it is a 'plist array' type and insert it with blank values.  

There are no actual templates stored anywhere but previously octool only read the first value in the acpi, kext, tool and driver sections.  Now it will do the same for any subsection that is inside a 'plist array'

The DeviceProperties/Add section is a 'plist dict' with no standard fields, so no real way to auto generate a blank template from it on the fly.  It would just be a blank 'plist dict' with nothing in it.  So, the user will still need to make it themselves or copy-paste one of the existing items and edit the new item.  

If Acidanthera changes the DeviceProperties/Add section to an array then octool will automatically generate a template without the need to change any code.  But if they don't, then it won't.

**Comment by dreamwhite** [comment]
Ohhh thank you so much! Feel free of dming me for faster feedbacks and tests with beta releases via matrix.org: `@dreamwhitedev:matrix.org`
